###
POST http://localhost:8000/api/v1/fan/status
Content-Type: application/json

{
    "state": "on"
}
###
POST http://localhost:8000/api/v1/fan/status
Content-Type: application/json

{
    "state": "off"
}

###
POST http://localhost:8000/api/v1/air/status
Content-Type: application/json

{
    "state": "on"
}
###
POST http://localhost:8000/api/v1/air/status
Content-Type: application/json

{
    "state": "off"
}
###
POST http://localhost:8000/api/v1/lamp/status
Content-Type: application/json

{
    "state": "on"
}
###
POST http://localhost:8000/api/v1/lamp/status
Content-Type: application/json

{
    "state": "off"
}

###
http://localhost:8000/history-action?startDate=2024-08-19&endDate=2024-08-20

###
GET http://localhost:8000/sensors?page=1&limit=10&startDate=2024-08-19&endDate=2024-08-22&keyword=33&searchBy=temperature&sortBy=humidity&typeSort=desc
